// <auto-generated />
using System;
using Infrastructure.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Presistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240107123204_NameChange")]
    partial class NameChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ccb5426-b94e-44dd-a5f9-31478baaac89"),
                            CreatedAtDateTime = new DateTime(2024, 1, 7, 12, 32, 4, 411, DateTimeKind.Utc).AddTicks(9222),
                            Email = "marshall.simmons@example.com",
                            Name = "Marshall Simmons",
                            PhoneNumber = "(309) 822-2653",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("054fbf21-a875-4296-bc56-0cd6b056a310"),
                            CreatedAtDateTime = new DateTime(2024, 1, 7, 12, 32, 4, 411, DateTimeKind.Utc).AddTicks(9232),
                            Email = "victoria.west@example.com",
                            Name = "Victoria West",
                            PhoneNumber = "(603) 232-6206",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
