// <auto-generated />
using System;
using Infrastructure.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Presistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106163625_SeedTeamMembers")]
    partial class SeedTeamMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TeamMemeber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5caf1fda-c0fd-49dd-8622-058e98b0f2b9"),
                            CreatedAtDateTime = new DateTime(2024, 1, 6, 16, 36, 25, 826, DateTimeKind.Utc).AddTicks(5089),
                            Email = "marshall.simmons@example.com",
                            Name = "Marshall Simmons",
                            PhoneNumber = "(309) 822-2653",
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("71a01fea-76d2-4eb4-b305-f3d5c0fea561"),
                            CreatedAtDateTime = new DateTime(2024, 1, 6, 16, 36, 25, 826, DateTimeKind.Utc).AddTicks(5099),
                            Email = "victoria.west@example.com",
                            Name = "Victoria West",
                            PhoneNumber = "(603) 232-6206",
                            State = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
